---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-crew
  namespace: minecraft-crew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-crew
  template:
    metadata:
      labels:
        app: minecraft-crew
    spec:    
      volumes:
      - name: minecraft-crew
        persistentVolumeClaim:
          claimName: minecraft-crew
      containers:
      - name: minecraft-crew
        image: ghcr.io/jwklijnsma/minecraft-crew:main
        volumeMounts:
          - name: minecraft-crew
            mountPath: /home/alex/minecraft
        ports:
        - containerPort: 25565
          hostPort: 25565
          name: minecraft-crew
          protocol: UDP
        - containerPort: 25565
          hostPort: 25565
          name: minecraft-crew
          protocol: TCP
        - containerPort: 19132
          hostPort: 19132
          name: minecraft-crew
          protocol: UDP
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.0.4.2
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-crew
  namespace: minecraft-crew
spec:
  ports:
  - name: minecraft-crew
    port: 25565
    protocol: UDP
    targetPort: 25565
  - name: minecraft-crew
    port: 25565
    protocol: TCP
    targetPort: 25565
  - name: minecraft-crew
    port: 19132
    protocol: UDP
    targetPort: 19132
  selector:
    app: minecraft-crew
  type: 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-crew
  namespace: minecraft-crew-minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
